### PR TITLE
Doc: highlight that setBfree -H is a long and great doc !

### PR DESCRIPTION
**Pull request by brunetton**
Hi, I'm using setBfree for a while now, and I always scratched my head wondering: where is the doc ?? Just "discovered" `setBfree -H` to be a more more detailed doc than `setBfreeUI -h` (and I didn't noticed that little line inside `setBfree -h` telling me that there's actually a great doc).
This great doc should be highlighted in readme !

### CODE REVIEW

**Comment by x42** [comment]
Why "disable ui animations" ? did that slip in by accident?

**Comment by x42** [comment]
I've applied the change to the readme in e706bf0845. Thanks!

**Comment by brunetton** [comment]
My pleasure ! Thanks to you

2018-03-24 0:47 GMT+01:00 Robin Gareus <notifications@github.com>:

**Comment by brunetton** [comment]
> Why "disable ui animations" ? did that slip in by accident?

Totally ! Really sorry for this, but you understood it was a mistake. Sorry for that !

**Pull request closed without merging**
