### PR TITLE
Fix gl linking

### PR DESCRIPTION
**Pull request by Ast-x64**

### CODE REVIEW

**Comment by x42** [comment]
I'm curious which, on which  distro is this needed? libglu requires libgl (or an equivalent). It should not be needed to specify libgl explicitly. 

Here on debian, I get the following:

```bash
$ pkg-config --libs glu 
-lGLU -lGL
$ pkg-config --libs gl glu 
-lGLU -lGL
```

**Comment by Ast-x64** [comment]
> I'm curious which, on which distro is this needed? libglu requires libgl (or an equivalent). It should not be needed to specify libgl explicitly.
> 
> Here on debian, I get the following:
> 
> ```shell
> $ pkg-config --libs glu 
> -lGLU -lGL
> $ pkg-config --libs gl glu 
> -lGLU -lGL
> ```

Thanks for your reply. I'm on archlinux and I get the following:

```
sh-5.1# pkg-config --libs glu
-lGLU
sh-5.1# pkg-config --libs gl
-lGL
```

**Comment by x42** [comment]
I just talked to an arch developer. Arch ships a bleeding-edge, build of libglu (using meson to build it instead of autotools).

The issue was fixed upstream https://cgit.freedesktop.org/mesa/glu/commit/?id=225e00a14a9200f11253775a7c7778c1c29c8b23  and once arch picks up new libglu, the problem will go away.

**Comment by x42** [comment]
It was just updated in Arch: "upgpkg: glu 9.0.2-2: fix pkgconfig file"

https://github.com/archlinux/svntogit-packages/commit/5c060791cfc60ed6fecf4400423498281b947b12

**Comment by Ast-x64** [comment]
Thanks for your reply. I'll close this pr.

**Pull request closed without merging**
